### ISSUE TITLE
 AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by dingtom** [keras-team/autokeras#1095]
i have run keras_cnn.ipynb which copy from offical website in colab, but i got an error  AttributeError: 'tuple' object has no attribute 'shape'

**Comment by haifeng-jin** [comment]
Thank you for the report. It has been fixed in the master branch

**Comment by iirekm** [comment]
+1

On Ubuntu 20, autokeras 1.0.2, and the official example:
```python
import autokeras as ak

# Initialize the classifier.
clf = ak.StructuredDataClassifier(max_trials=30)
# x is the path to the csv file. y is the column name of the column to predict.
clf.fit(x='/home/irek/Pobrane/train.txt', y='survived')
# Evaluate the accuracy of the found model.
print('Accuracy: {accuracy}'.format(
    accuracy=clf.evaluate(x='/home/irek/Pobrane/eval.txt', y='survived')))
```

```
2020-05-31 17:41:11.061524: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-31 17:41:11.082875: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2494195000 Hz
2020-05-31 17:41:11.083416: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4ec6d50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-31 17:41:11.083442: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Epoch 1/1000
Traceback (most recent call last):
  File "/home/irek/workspace/varia-private/qtrading/ak.py", line 6, in <module>
    clf.fit(x='/home/irek/Pobrane/train.txt', y='survived')
  File "/home/irek/.venv/lib/python3.8/site-packages/autokeras/tasks/structured_data.py", line 246, in fit
    super().fit(x=x,
  File "/home/irek/.venv/lib/python3.8/site-packages/autokeras/tasks/structured_data.py", line 89, in fit
    super().fit(x=x,
  File "/home/irek/.venv/lib/python3.8/site-packages/autokeras/auto_model.py", line 253, in fit
    self.tuner.search(x=dataset,
  File "/home/irek/.venv/lib/python3.8/site-packages/autokeras/engine/tuner.py", line 114, in search
    super().search(callbacks=new_callbacks, **fit_kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/kerastuner/engine/base_tuner.py", line 130, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/autokeras/engine/tuner.py", line 71, in run_trial
    history = model.fit(x, *fit_args, **copied_fit_kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 505, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:543 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:391 update_state
        self._build(y_pred, y_true)
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:321 _build
        self._metrics = nest.map_structure_up_to(y_pred, self._get_metric_objects,
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1114 map_structure_up_to
        return map_structure_with_tuple_paths_up_to(
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1213 map_structure_with_tuple_paths_up_to
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /home/irek/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:442 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'
```

**Comment by madhubandru** [comment]
+1

Facing same error.

IDE: Juypter notebook

------------------------------------------------
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

import autokeras as ak

clf = ak.ImageClassifier(max_trials=10) 
clf.fit(x_train, y_train,epochs=3)
---------------------------------------------------

`Epoch 1/3
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-dbbd6c2b9b86> in <module>
      5 
      6 clf = ak.ImageClassifier(max_trials=10)
----> 7 clf.fit(x_train, y_train,epochs=3)

~/anaconda3/lib/python3.7/site-packages/autokeras/tasks/image.py in fit(self, x, y, epochs, callbacks, validation_split, validation_data, **kwargs)
    120                     validation_split=validation_split,
    121                     validation_data=validation_data,
--> 122                     **kwargs)
    123 
    124 

~/anaconda3/lib/python3.7/site-packages/autokeras/auto_model.py in fit(self, x, y, batch_size, epochs, callbacks, validation_split, validation_data, **kwargs)
    256                           validation_data=validation_data,
    257                           fit_on_val_data=self._split_dataset,
--> 258                           **kwargs)
    259 
    260     def _process_x(self, x, fit):

~/anaconda3/lib/python3.7/site-packages/autokeras/engine/tuner.py in search(self, callbacks, fit_on_val_data, **fit_kwargs)
    112             new_callbacks.append(tf.keras.callbacks.EarlyStopping(patience=10))
    113 
--> 114         super().search(callbacks=new_callbacks, **fit_kwargs)
    115 
    116         # Fully train the best model with original callbacks.

~/anaconda3/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py in search(self, *fit_args, **fit_kwargs)
    128 
    129             self.on_trial_begin(trial)
--> 130             self.run_trial(trial, *fit_args, **fit_kwargs)
    131             self.on_trial_end(trial)
    132         self.on_search_end()

~/anaconda3/lib/python3.7/site-packages/autokeras/engine/tuner.py in run_trial(self, trial, x, *fit_args, **fit_kwargs)
     69             model = self.hypermodel.build(trial.hyperparameters)
     70             utils.adapt_model(model, x)
---> 71             history = model.fit(x, *fit_args, **copied_fit_kwargs)
     72             for metric, epoch_values in history.history.items():
     73                 if self.oracle.objective.direction == 'min':

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    625       # This is the first call of __call__, so we have to initialize.
    626       initializers = []
--> 627       self._initialize(args, kwds, add_initializers_to=initializers)
    628     finally:
    629       # At this point we know that the initialization is complete (or less

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    504     self._concrete_stateful_fn = (
    505         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 506             *args, **kwds))
    507 
    508     def invalid_creator_scope(*unused_args, **unused_kwds):

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2444       args, kwargs = None, None
   2445     with self._lock:
-> 2446       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2447     return graph_function
   2448 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2775 
   2776       self._function_cache.missed.add(call_context_key)
-> 2777       graph_function = self._create_graph_function(args, kwargs)
   2778       self._function_cache.primary[cache_key] = graph_function
   2779       return graph_function, args, kwargs

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2665             arg_names=arg_names,
   2666             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2667             capture_by_value=self._capture_by_value),
   2668         self._function_attributes,
   2669         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980 
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982 
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    439         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    440         # the function a weak reference to itself to avoid a reference cycle.
--> 441         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    442     weak_wrapped_fn = weakref.ref(wrapped_fn)
    443 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

AttributeError: in user code:

    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:543 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:391 update_state
        self._build(y_pred, y_true)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:322 _build
        self._metrics, y_true, y_pred)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/madhubandru/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:442 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'`

**Comment by KirkDCO** [comment]
Same problem here using official example from https://autokeras.com/tutorial/structured_data_classification/

Environment:
MacOS
Python 3.8
autokeras 1.0.2
tensorflow 2.2.0

-------------------------------
Epoch 1/1000
Traceback (most recent call last):
  File "ak_tutorial.py", line 11, in <module>
    clf.fit(x_train, y_train)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/autokeras/tasks/structured_data.py", line 246, in fit
    super().fit(x=x,
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/autokeras/tasks/structured_data.py", line 89, in fit
    super().fit(x=x,
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/autokeras/auto_model.py", line 253, in fit
    self.tuner.search(x=dataset,
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/autokeras/engine/tuner.py", line 114, in search
    super().search(callbacks=new_callbacks, **fit_kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/kerastuner/engine/base_tuner.py", line 130, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/autokeras/engine/tuner.py", line 71, in run_trial
    history = model.fit(x, *fit_args, **copied_fit_kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 505, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:543 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:391 update_state
        self._build(y_pred, y_true)
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:321 _build
        self._metrics = nest.map_structure_up_to(y_pred, self._get_metric_objects,
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1114 map_structure_up_to
        return map_structure_with_tuple_paths_up_to(
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1213 map_structure_with_tuple_paths_up_to
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/kdelisle/opt/miniconda2/envs/AutoML/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:442 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'

**Comment by achaar** [comment]
@KirkDCO Have you tried using the master branch?
If not, install using the AutoKeras master branch.

Thanks.

**Comment by KirkDCO** [comment]
Yes, to both.  

I pulled from the master branch yesterday (20.06.01) and tf is 2.2.0 installed by pip.

Note that I'm also having errors with another example - issue report here:  https://github.com/keras-team/autokeras/issues/1163

**Comment by haifeng-jin** [comment]
Hi everyone, I am really sorry about the bugs.
I am busy fixing them and aiming at a new stable release soon.
If you have to get it working now, please try our master branch with the master branch of keras-tuner and tensorflow 2.2.0 as dependency.

Thanks.
```
pip install git+https://github.com/keras-team/autokeras.git@master
pip install git+https://github.com/keras-team/keras-tuner.git@master
pip install tensorflow==2.2.0
```

**Comment by cibic89** [comment]
> Hi everyone, I am really sorry about the bugs.
> I am busy fixing them and aiming at a new stable release soon.
> If you have to get it working now, please try our master branch with the master branch of keras-tuner and tensorflow 2.2.0 as dependency.
> 
> Thanks.
> 
> ```
> pip install git+https://github.com/keras-team/autokeras.git@master
> pip install git+https://github.com/keras-team/keras-tuner.git@master
> pip install tensorflow==2.2.0
> ```

This works for me now!!

**Comment by hello10242048** [comment]
> > Hi everyone, I am really sorry about the bugs.
> > I am busy fixing them and aiming at a new stable release soon.
> > If you have to get it working now, please try our master branch with the master branch of keras-tuner and tensorflow 2.2.0 as dependency.
> > Thanks.
> > ```
> > pip install git+https://github.com/keras-team/autokeras.git@master
> > pip install git+https://github.com/keras-team/keras-tuner.git@master
> > pip install tensorflow==2.2.0
> > ```
> 
> This works for me now!!

No, it does not work for me

**Comment by hello10242048** [comment]
> Hi everyone, I am really sorry about the bugs.
> I am busy fixing them and aiming at a new stable release soon.
> If you have to get it working now, please try our master branch with the master branch of keras-tuner and tensorflow 2.2.0 as dependency.
> 
> Thanks.
> 
> ```
> pip install git+https://github.com/keras-team/autokeras.git@master
> pip install git+https://github.com/keras-team/keras-tuner.git@master
> pip install tensorflow==2.2.0
> ```

TypeError Traceback (most recent call last)

in ()
16 #outputs=[ak.ClassificationHead()],
17 max_trials=global_max_trials,
---> 18 objective = 'val_loss',
19 #overwrite=global_overwrite,
20 #tuner='bayesian'

2 frames

/usr/local/lib/python3.6/dist-packages/autokeras/engine/tuner.py in init(self, oracle, hypermodel, preprocessors, **kwargs)
36 preprocessors=None,
37 **kwargs):
---> 38 super().init(oracle, hypermodel, **kwargs)
39 self.preprocessors = nest.flatten(preprocessors)
40 self._finished = False

TypeError: init() got an unexpected keyword argument 'name'

**Comment by haifeng-jin** [comment]
We have released a new version 1.0.3. You may use this to install:
```
pip3 install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0
pip3 install autokeras==1.0.3
```

**Comment by StuartIanNaylor** [comment]
@haifeng-jin Apols but tried the above

> pip3 install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0
> pip3 install autokeras==1.0.3

pip3 install tensorflow==2.2.0 but still

```
compile_utils.py:442 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'
```
Ubuntu 20.04

**Comment by GuillaumeLab** [comment]
same here, running :
pip3 install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0
pip3 install autokeras==1.0.3

 using the example for text classification : https://autokeras.com/tutorial/text_classification/

getting AttributeError: 'tuple' object has no attribute 'shape'

**Comment by haifeng-jin** [comment]
Yes, that version is not working with the latest tf.
So please use autokeras 1.0.9 and tf 2.3.0 and keras-tuner 1.0.2rc2.
You can follow the installation instructions on our website. Thanks.

**Comment by StuartIanNaylor** [comment]
@haifeng-jin tf 2.3.0 has me in a catch-22 where Illegal instruction (core dumped) happens on importing TF.

Up to 2.2 works on a I5 3570 so now stuck between the 2?

**Comment by haifeng-jin** [comment]
core dump may be caused by too large models. According to our tests, the latest version should work with tf 2.4.0 and tf 2.3.0.

**Comment by LucaUrbinati44** [comment]
I solved with:

Python 3.7.10
Autokeras 1.0.12
Keras-Tuner 1.0.2
TensorFlow 2.4.1

**Comment by loheden** [comment]
On Mac OS M1, when I try to install autokeras 1.0.12, I get the following error:

(python38) tfrecord_files % pip install autokeras==1.0.12
Collecting autokeras==1.0.12
  Using cached autokeras-1.0.12-py3-none-any.whl (164 kB)
Requirement already satisfied: scikit-learn in /Users/me/miniforge3/envs/python38/lib/python3.8/site-packages (from autokeras==1.0.12) (0.24.2)
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.3.0 (from autokeras) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.3.0


How am I supposed to solve this problem? Spent countless number of hours on this issue now..

**Comment by STRATZ-Ken** [comment]
I am seeing this issue on Keras-Tuner 1.1.0, Keras 2.8.0 and Tensorflow-gpu 2.8.0.  Python 3.9.
