### ISSUE TITLE
Multiple inputs 

### ISSUE THREAD

**Issue by borisRa** [keras-team/autokeras#1277]
### Feature Description

To be able to get multiple network inputs

### Code Example

```python
  input_node_1 = ak.Input()  
  input_node_2 = ak.Input() 
	
	
  input_node_1 = ak.ConvBlock()(input_node_1) 
  concanted_ONE_input = ak.Merge(merge_type="concatenate")([input_node_1,input_node_2])
  X = ak.DenseBlock()(concanted_ONE_input) #optional
	
	
  output_node = ak.RegressionHead(output_dim = last_layer_size,loss =tf.keras.losses.MAE )(X)#Head is the last layer ( end of the network)
  auto_model = ak.AutoModel(inputs= input_node_1,input_node_2],outputs=output_node,overwrite=True,max_trials=100,tuner="greedy")

  #The error is : AttributeError: 'Node' object has no attribute 'get_adapter'
```

**Comment by haifeng-jin** [comment]
I think this example should work in 1.0.5. Which version are you using now? Thanks.

**Comment by borisRa** [comment]
The version is 1.0.5

**Comment by masatatsu8** [comment]
I'm using 1.0.8 and got the same error with the simpler codes

```Python
input_node = ak.Input()
output_node = ak.DenseBlock(use_batchnorm=False)(input_node)
auto_model = ak.AutoModel(inputs=input_node, outputs=output_node, overwrite=True, max_trials=2)

# The error is :  AttributeError: 'DenseBlock' object has no attribute 'get_adapter'
```

**Comment by haifeng-jin** [comment]
I believe this is fixed in the master branch. If you like to check it out.
