### ISSUE TITLE
AttributeError in Image Classification Tutorial 

### ISSUE THREAD

**Issue by pymacbit** [keras-team/autokeras#1132]
### Bug Description

After executing ImageClassifier cell it says AttributeError: 'tuple' object has no attribute 'shape'

**Comment by bichengcao** [comment]
I had the same issue on Python 3.8.3 and Tensorflow 2.2.0. But it works on Python 3.7.7 and Tensorflow 2.1.1.

The issue is probably in Tensorflow 2.2.0, but Python 3.8.3 doesn't support Tensorflow 2.1. So I have to use Python 3.7 to make it work.

**Comment by haifeng-jin** [comment]
This is now fixed with AK 1.0.3. Thanks.
